### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by glixx** [spiderbit/canta#8] opened 2013-05-10 12:56 UTC
Start:

*removed Dummy to another bug

**Comment by glixx** [comment] 2013-05-10 13:54
#Fix localization
sed -i -e "s/str(_('Genre: '))/_('Genre: ')/g" ./canta/menus/browser_entry.py
sed -i -e "s/str(_('Edition: '))/_('Edition: ')/g" ./canta/menus/browser_entry.py
sed -i -e "s/str(_('Creator: '))/_('Creator: ')/g" ./canta/menus/browser_entry.py
sed -i -e "s/str(_('BPM: '))/_('BPM: ')/g" ./canta/menus/browser_entry.py

**Comment by spiderbit** [comment] 2013-05-10 15:20
"Start:" is fixed in newest commit from the branch propose_0.2

**Comment by spiderbit** [comment] 2013-05-10 19:03
need updated po-file from you for russion language because I added the "Start" string

**Comment by spiderbit** [comment] 2013-05-10 23:06
I kind of see that bug fixed for 0.2 I added the Start String, "Dummy" is not that importent I think, I could remove that selection box maybe ^^ and set it fixed to gstreamer ^^ that would maybe fix that ^^ But why would you change that if gstreamer works very good ^^

yes of course its a small localisation task/bug but I dont know if my spare time is invested good into fixing such minor problems in a old version.

I mean if I as example could bring the version 0.3 in a regression-free state it would fix that crash bug on save and restart.

But ok I let that bug open for now.

**Comment by spiderbit** [comment] 2013-05-12 22:34
splited this bug in 2 seperate ones, Dummy and other option-translations is in #23 

this bug is fixed in propose_0.2 tree

**Closed as completed by spiderbit** 2013-05-12 22:34 UTC
